# Generated by Django 3.0.4 on 2020-03-18 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParticipantName', models.CharField(max_length=100, null=True)),
                ('ParticipantEmail', models.EmailField(max_length=50, null=True)),
                ('ParticipantPhNo', models.CharField(max_length=10, null=True)),
                ('ParticipantUSN', models.CharField(max_length=10, null=True)),
                ('ParticipantDOB', models.DateField(default=datetime.date.today, null=True)),
                ('ParticipantSem', models.CharField(choices=[('2ndSem', 'Second Semester'), ('4thSem', 'Fourth Semester'), ('6thSem', 'Sixth Semester'), ('8thSem', 'Eighth Semester')], default='2ndSem', max_length=50, null=True)),
                ('ParticipantImage', models.ImageField(max_length=1000, upload_to='Images/')),
                ('Event1', models.BooleanField(default=False)),
                ('Event2', models.BooleanField(default=False)),
                ('Event3', models.BooleanField(default=False)),
                ('Event4', models.BooleanField(default=False)),
                ('Event5', models.BooleanField(default=False)),
                ('Event6', models.BooleanField(default=False)),
                ('Event7', models.BooleanField(default=False)),
                ('Event8', models.BooleanField(default=False)),
                ('Event9', models.BooleanField(default=False)),
                ('Event10', models.BooleanField(default=False)),
                ('Event11', models.BooleanField(default=False)),
                ('Event12', models.BooleanField(default=False)),
                ('Event13', models.BooleanField(default=False)),
                ('Event14', models.BooleanField(default=False)),
                ('Event15', models.BooleanField(default=False)),
            ],
        ),
    ]
